export const escapeHTML=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
export const icon=(name,label='')=>`<i class="fa-solid fa-${name}" ${label?`aria-label="${label}"`:'aria-hidden="true"'}></i>`;
export const formatDate=v=>v?new Intl.DateTimeFormat('en',{day:'numeric',month:'short',year:'numeric'}).format(new Date(v)):'To be announced';
export const relativeDate=v=>{if(!v)return'Date pending';const d=Math.ceil((new Date(v)-Date.now())/86400000);return d<0?'Closed':d===0?'Closes today':`${d} day${d===1?'':'s'} left`};
export const titleCase=v=>String(v||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
export const logo=()=>`<a class="brand" href="/" data-link><img src="/assets/logo.png" alt=""><span>VERTEX</span></a>`;
export const avatar=p=>p?.avatar_url?`<img class="avatar" src="${escapeHTML(p.avatar_url)}" alt="">`:`<span class="avatar avatar-fallback">${escapeHTML(p?.full_name?.[0]||'V')}</span>`;
const activeFor=(href,p)=>href==='/dashboard'?(p==='/dashboard'||p.startsWith('/manage')):p===href;
const navLink=(href,label,i,p)=>`<a class="${activeFor(href,p)?'active':''}" href="${href}" data-link>${i?icon(i):''}<span>${label}</span></a>`;
export const shell=(content,state={})=>{const p=location.pathname,role=state.profile?.account_type;let links=[];if(!state.user||role==='participant')links=[['/discover','Discover','compass'],...(state.user?[['/dashboard','Dashboard','layer-group'],['/saved','Saved','bookmark']]:[])];else links=[['/dashboard','Dashboard','layer-group']];const theme=document.documentElement.dataset.theme||'light';return`
<header class="site-header"><div class="header-inner">${logo()}<nav class="desktop-nav" aria-label="Main">${links.map(x=>navLink(...x,p)).join('')}</nav><div class="header-actions"><button class="icon-button theme-button" data-theme-toggle aria-label="Switch to ${theme==='dark'?'light':'dark'} mode">${icon(theme==='dark'?'sun':'moon')}</button>${state.user?`<a class="icon-button notification-link ${p==='/notifications'?'active':''}" href="/notifications" data-link aria-label="Notifications">${icon('bell')}</a><a class="profile-link ${p==='/profile'?'active':''}" href="/profile" data-link aria-label="Open profile">${avatar(state.profile)}</a><button class="quiet-button" data-signout>Sign out</button>`:`<a class="quiet-button" href="/login" data-link>Log in</a><a class="button small" href="/signup" data-link>Join Vertex</a>`}</div></div></header><main id="app-main" class="page-transition">${content}</main>${state.user?`<nav class="mobile-nav" aria-label="Mobile">${links.map(x=>navLink(...x,p)).join('')}${navLink('/notifications','Alerts','bell',p)}${navLink('/profile','Profile','user',p)}</nav>`:''}<div class="install-prompt" data-install hidden><img src="/assets/logo.png" alt=""><div><strong>Keep Vertex close</strong><span>Install for faster access and alerts.</span></div><button class="button small" data-install-button>Install</button><button class="icon-button install-close" data-install-dismiss aria-label="Dismiss">${icon('xmark')}</button></div>`};
export const emptyState=(i,t,x,a='')=>`<div class="empty-state">${icon(i)}<h3>${t}</h3><p>${x}</p>${a}</div>`;
export const toast=(message,type='success')=>{const el=document.createElement('div');el.className=`toast ${type}`;el.innerHTML=`${icon(type==='success'?'circle-check':'circle-exclamation')}<span>${escapeHTML(message)}</span>`;document.querySelector('#toast-region')?.append(el);setTimeout(()=>el.remove(),3600)};
export const field=(label,name,type='text',extra='')=>`<label class="field"><span>${label}</span><input name="${name}" type="${type}" ${extra}></label>`;
export const competitionCard=(c,saved=false,canSave=false)=>{const bg=c.banner_style==='gradient'?`linear-gradient(135deg,${c.banner_color||'#2563eb'},${c.banner_secondary_color||'#7c3aed'})`:`linear-gradient(135deg,${c.banner_color||'#2563eb'},color-mix(in srgb,${c.banner_color||'#2563eb'},#0b1120 42%))`;return`<article class="competition-card pointer-card" style="--card-bg:${bg}"><a href="/competition/${escapeHTML(c.slug)}" data-link class="card-hit" aria-label="View ${escapeHTML(c.name)}"></a><div class="card-banner">${c.banner_url?`<img src="${escapeHTML(c.banner_url)}" alt="">`:''}<span class="status-chip">${escapeHTML(c.status==='ongoing'?'In progress':'Registration open')}</span>${canSave?`<button class="bookmark ${saved?'saved':''}" data-bookmark data-id="${c.id}" aria-label="${saved?'Remove saved competition':'Save competition'}">${icon('bookmark')}</button>`:''}</div><div class="card-content"><div class="tags">${(c.competition_tags||[]).slice(0,2).map(x=>`<span>${escapeHTML(x.tag?.name)}</span>`).join('')}</div><h3>${escapeHTML(c.name)}</h3><p>${escapeHTML(c.organisation?.name||'Independent organiser')}</p><div class="card-meta"><span>${icon('users')} ${c.team_mode==='individual'?'Individual':c.team_mode==='team'?'Teams':'Individual or teams'}</span><span>${icon('trophy')} ${escapeHTML(c.prize_summary||'Prize details pending')}</span></div><div class="deadline-rail"><span style="--progress:64%"></span><strong>${relativeDate(c.registration_deadline)}</strong><small>Registration deadline · ${formatDate(c.registration_deadline)}</small></div></div></article>`};
