-- Vertex complete Supabase setup. Run once in SQL Editor.
create extension if not exists pgcrypto;
create type public.account_type as enum ('participant','organiser','organisation');
create type public.competition_status as enum ('draft','published','ongoing','completed','archived');
create type public.team_mode as enum ('individual','team','both');
create type public.registration_status as enum ('pending','confirmed','eliminated','withdrawn');
create type public.submission_mode as enum ('files','links','mixed');

create table public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 username text not null unique check(username ~ '^[a-zA-Z0-9_]{3,24}$'),
 full_name text not null, account_type public.account_type not null default 'participant',
 bio text, avatar_url text, social_links jsonb not null default '[]', organisation_id uuid,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.organisations(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,description text,logo_url text,owner_id uuid references public.profiles(id),created_at timestamptz default now());
alter table public.profiles add constraint profiles_organisation_fk foreign key(organisation_id) references public.organisations(id) on delete set null;
create table public.competitions(
 id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,description text not null default '',
 organisation_id uuid references public.organisations(id),created_by uuid not null references public.profiles(id),
 status public.competition_status not null default 'draft',team_mode public.team_mode not null default 'individual',
 prize_summary text,prize_details text,age_min int check(age_min>=5),age_max int check(age_max<=30 and age_max>=age_min),
 banner_url text,banner_color text default '#2563EB',structure_type text not null default 'direct',
 registration_deadline timestamptz not null,start_at timestamptz,end_at timestamptz,certificate_release_at timestamptz,
 scores_public boolean not null default false,created_at timestamptz default now(),updated_at timestamptz default now()
);
create table public.tags(id bigint generated always as identity primary key,name text not null unique,slug text not null unique);
insert into public.tags(name,slug) values ('Mathematics','mathematics'),('Physics','physics'),('Programming','programming'),('Research','research'),('Writing','writing'),('Design','design'),('Business','business'),('Science','science');
create table public.competition_tags(competition_id uuid references public.competitions on delete cascade,tag_id bigint references public.tags on delete cascade,primary key(competition_id,tag_id));
create table public.rounds(id uuid primary key default gen_random_uuid(),competition_id uuid not null references public.competitions on delete cascade,name text not null,slug text not null,position int not null,advance_count int,submission_deadline timestamptz,results_release_at timestamptz,results_released boolean default false,unique(competition_id,slug),unique(competition_id,position));
create table public.categories(id uuid primary key default gen_random_uuid(),competition_id uuid not null references public.competitions on delete cascade,name text not null,unique(competition_id,name));
create table public.competition_organisers(competition_id uuid references public.competitions on delete cascade,profile_id uuid references public.profiles on delete cascade,role text not null default 'organiser',accepted boolean default false,primary key(competition_id,profile_id));
create table public.registrations(id uuid primary key default gen_random_uuid(),competition_id uuid not null references public.competitions on delete cascade,participant_id uuid not null references public.profiles on delete cascade,category_id uuid references public.categories,status public.registration_status not null default 'confirmed',registered_name text not null default '',created_at timestamptz default now(),unique(competition_id,participant_id));
create table public.teams(id uuid primary key default gen_random_uuid(),competition_id uuid not null references public.competitions on delete cascade,name text not null,created_by uuid not null references public.profiles,category_id uuid references public.categories,created_at timestamptz default now(),unique(competition_id,name));
create table public.team_members(team_id uuid references public.teams on delete cascade,participant_id uuid references public.profiles on delete cascade,invite_status text not null default 'pending',is_captain boolean default false,primary key(team_id,participant_id));
create table public.announcements(id uuid primary key default gen_random_uuid(),competition_id uuid not null references public.competitions on delete cascade,author_id uuid not null references public.profiles,title text not null,body text not null,push_enabled boolean default true,created_at timestamptz default now());
create table public.questions(id uuid primary key default gen_random_uuid(),competition_id uuid not null references public.competitions on delete cascade,author_id uuid not null references public.profiles,body text not null,created_at timestamptz default now());
create table public.answers(id uuid primary key default gen_random_uuid(),question_id uuid not null references public.questions on delete cascade,author_id uuid not null references public.profiles,body text not null,created_at timestamptz default now());
create table public.meetings(id uuid primary key default gen_random_uuid(),competition_id uuid not null references public.competitions on delete cascade,name text not null,slug text not null,jitsi_room text not null,starts_at timestamptz,created_by uuid references public.profiles,unique(competition_id,slug),unique(competition_id,name));
create table public.meeting_assignments(meeting_id uuid references public.meetings on delete cascade,participant_id uuid references public.profiles on delete cascade,team_id uuid references public.teams on delete cascade,check((participant_id is null)<>(team_id is null)));
create table public.submission_boxes(id uuid primary key default gen_random_uuid(),round_id uuid not null references public.rounds on delete cascade,mode public.submission_mode not null,allowed_types text[] default '{}',size_limit_mb numeric not null default 25 check(size_limit_mb>0 and size_limit_mb<=25),instructions text,is_open boolean default true,unique(round_id));
create table public.submissions(id uuid primary key default gen_random_uuid(),box_id uuid not null references public.submission_boxes on delete cascade,participant_id uuid references public.profiles,team_id uuid references public.teams,file_paths text[] default '{}',links text[] default '{}',submitted_at timestamptz default now(),check((participant_id is null)<>(team_id is null)),unique(box_id,participant_id),unique(box_id,team_id));
create table public.scoring_criteria(id uuid primary key default gen_random_uuid(),round_id uuid not null references public.rounds on delete cascade,name text not null,max_score numeric not null check(max_score>0),weight numeric not null default 1,position int not null,unique(round_id,name));
create table public.scores(id uuid primary key default gen_random_uuid(),criterion_id uuid not null references public.scoring_criteria on delete cascade,registration_id uuid references public.registrations on delete cascade,team_id uuid references public.teams on delete cascade,score numeric not null check(score>=0),scored_by uuid references public.profiles,updated_at timestamptz default now(),check((registration_id is null)<>(team_id is null)),unique(criterion_id,registration_id),unique(criterion_id,team_id));
create table public.leaderboards(id uuid primary key default gen_random_uuid(),round_id uuid not null references public.rounds on delete cascade,release_at timestamptz not null,published_at timestamptz,show_scores boolean default false,unique(round_id));
create table public.leaderboard_entries(id uuid primary key default gen_random_uuid(),leaderboard_id uuid not null references public.leaderboards on delete cascade,registration_id uuid references public.registrations,team_id uuid references public.teams,rank int not null,score numeric,placement text,category_id uuid references public.categories,advances boolean default false,check((registration_id is null)<>(team_id is null)),unique(leaderboard_id,rank));
create table public.qualifications(id uuid primary key default gen_random_uuid(),competition_id uuid not null references public.competitions on delete cascade,participant_id uuid not null references public.profiles on delete cascade,round_id uuid references public.rounds,tag text not null,awarded_at timestamptz default now(),unique(competition_id,participant_id,tag));
create table public.certificate_templates(id uuid primary key default gen_random_uuid(),competition_id uuid not null references public.competitions on delete cascade,name text not null,image_path text not null,eligibility_tags text[] default '{"participant"}',dynamic_fields jsonb not null default '[]',output_format text default 'pdf',enabled boolean default false,created_at timestamptz default now());
create table public.notifications(id uuid primary key default gen_random_uuid(),recipient_id uuid not null references public.profiles on delete cascade,type text not null,title text not null,body text,link text,read_at timestamptz,created_at timestamptz default now());
create table public.push_subscriptions(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles on delete cascade,endpoint text not null unique,p256dh text not null,auth text not null,created_at timestamptz default now());
create table public.achievements(id bigint generated always as identity primary key,code text not null unique,name text not null,description text not null,icon text not null,threshold int not null);
create table public.profile_achievements(profile_id uuid references public.profiles on delete cascade,achievement_id bigint references public.achievements on delete cascade,unlocked_at timestamptz default now(),primary key(profile_id,achievement_id));
create table public.bookmarks(profile_id uuid references public.profiles on delete cascade,competition_id uuid references public.competitions on delete cascade,created_at timestamptz default now(),primary key(profile_id,competition_id));
insert into public.achievements(code,name,description,icon,threshold) values('first_step','First step','Enter your first competition','flag',1),('momentum','Momentum','Complete five competitions','bolt',5),('team_player','Team player','Enter three team competitions','users',3);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,username,full_name,account_type) values(new.id,lower(coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1)))||case when exists(select 1 from public.profiles where username=lower(coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1)))) then '_'||substr(new.id::text,1,6) else '' end,coalesce(new.raw_user_meta_data->>'full_name','Vertex member'),coalesce((new.raw_user_meta_data->>'account_type')::public.account_type,'participant'));return new;end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.is_comp_organiser(cid uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from competitions c where c.id=cid and c.created_by=auth.uid()) or exists(select 1 from competition_organisers co where co.competition_id=cid and co.profile_id=auth.uid() and co.accepted)$$;
create or replace function public.set_registered_name() returns trigger language plpgsql security definer set search_path=public as $$begin select full_name into new.registered_name from profiles where id=new.participant_id;return new;end$$;
create trigger registration_name before insert on public.registrations for each row execute procedure public.set_registered_name();

alter table public.profiles enable row level security;alter table public.organisations enable row level security;alter table public.competitions enable row level security;alter table public.competition_tags enable row level security;alter table public.rounds enable row level security;alter table public.categories enable row level security;alter table public.competition_organisers enable row level security;alter table public.registrations enable row level security;alter table public.teams enable row level security;alter table public.team_members enable row level security;alter table public.announcements enable row level security;alter table public.questions enable row level security;alter table public.answers enable row level security;alter table public.meetings enable row level security;alter table public.meeting_assignments enable row level security;alter table public.submission_boxes enable row level security;alter table public.submissions enable row level security;alter table public.scoring_criteria enable row level security;alter table public.scores enable row level security;alter table public.leaderboards enable row level security;alter table public.leaderboard_entries enable row level security;alter table public.qualifications enable row level security;alter table public.certificate_templates enable row level security;alter table public.notifications enable row level security;alter table public.push_subscriptions enable row level security;alter table public.profile_achievements enable row level security;alter table public.bookmarks enable row level security;

create policy "profiles public read" on public.profiles for select using(true);create policy "profile owner update" on public.profiles for update using(id=auth.uid());
create policy "organisations public read" on public.organisations for select using(true);create policy "organisation owner manage" on public.organisations for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy "published competitions public read" on public.competitions for select using(status<>'draft' or public.is_comp_organiser(id));create policy "organisers create competitions" on public.competitions for insert with check(created_by=auth.uid() and exists(select 1 from profiles where id=auth.uid() and account_type='organiser'));create policy "organisers update competitions" on public.competitions for update using(public.is_comp_organiser(id));
create policy "tags public read" on public.competition_tags for select using(true);create policy "rounds public read" on public.rounds for select using(true);create policy "categories public read" on public.categories for select using(true);
create policy "organiser team visible" on public.competition_organisers for select using(true);create policy "organiser team manage" on public.competition_organisers for all using(public.is_comp_organiser(competition_id)) with check(public.is_comp_organiser(competition_id));
create policy "registrations own or organiser read" on public.registrations for select using(participant_id=auth.uid() or public.is_comp_organiser(competition_id));create policy "participants register" on public.registrations for insert with check(participant_id=auth.uid());
create policy "teams competition visible" on public.teams for select using(true);create policy "participants create teams" on public.teams for insert with check(created_by=auth.uid());create policy "team membership visible" on public.team_members for select using(true);create policy "team membership manage" on public.team_members for all using(participant_id=auth.uid() or exists(select 1 from teams where id=team_id and created_by=auth.uid()));
create policy "announcements public read" on public.announcements for select using(true);create policy "announcements organiser write" on public.announcements for insert with check(public.is_comp_organiser(competition_id));
create policy "questions public read" on public.questions for select using(true);create policy "participants ask" on public.questions for insert with check(author_id=auth.uid());create policy "answers public read" on public.answers for select using(true);create policy "authenticated answer" on public.answers for insert with check(author_id=auth.uid());
create policy "assigned meetings read" on public.meetings for select using(public.is_comp_organiser(competition_id) or exists(select 1 from meeting_assignments ma where ma.meeting_id=id and (ma.participant_id=auth.uid() or ma.team_id in(select team_id from team_members where participant_id=auth.uid() and invite_status='accepted'))));create policy "meetings organiser manage" on public.meetings for all using(public.is_comp_organiser(competition_id)) with check(public.is_comp_organiser(competition_id));
create policy "submission boxes read" on public.submission_boxes for select using(true);create policy "own submissions" on public.submissions for select using(participant_id=auth.uid() or exists(select 1 from team_members where team_id=submissions.team_id and participant_id=auth.uid()) or public.is_comp_organiser((select r.competition_id from submission_boxes b join rounds r on r.id=b.round_id where b.id=box_id)));create policy "submit own entry" on public.submissions for insert with check(participant_id=auth.uid() or exists(select 1 from team_members where team_id=submissions.team_id and participant_id=auth.uid() and invite_status='accepted'));
create policy "criteria participants read" on public.scoring_criteria for select using(true);create policy "scores controlled read" on public.scores for select using(exists(select 1 from scoring_criteria sc join rounds r on r.id=sc.round_id join competitions c on c.id=r.competition_id where sc.id=criterion_id and (c.scores_public or public.is_comp_organiser(c.id))));
create policy "released leaderboards read" on public.leaderboards for select using(published_at<=now() or public.is_comp_organiser((select competition_id from rounds where id=round_id)));create policy "released entries read" on public.leaderboard_entries for select using(exists(select 1 from leaderboards l where l.id=leaderboard_id and l.published_at<=now()));
create policy "own qualifications" on public.qualifications for select using(participant_id=auth.uid() or public.is_comp_organiser(competition_id));create policy "certificate templates eligible read" on public.certificate_templates for select using(enabled or public.is_comp_organiser(competition_id));create policy "own notifications" on public.notifications for select using(recipient_id=auth.uid());create policy "own notification update" on public.notifications for update using(recipient_id=auth.uid());create policy "own push subscriptions" on public.push_subscriptions for all using(profile_id=auth.uid()) with check(profile_id=auth.uid());create policy "own achievements" on public.profile_achievements for select using(profile_id=auth.uid());create policy "own bookmarks" on public.bookmarks for all using(profile_id=auth.uid()) with check(profile_id=auth.uid());

insert into storage.buckets(id,name,public,file_size_limit) values('banners','banners',true,26214400),('avatars','avatars',true,5242880),('submissions','submissions',false,26214400),('certificate-templates','certificate-templates',false,26214400) on conflict(id) do nothing;
create policy "public media read" on storage.objects for select using(bucket_id in('banners','avatars'));create policy "authenticated media upload" on storage.objects for insert to authenticated with check(bucket_id in('banners','avatars','submissions','certificate-templates') and (storage.foldername(name))[1]=auth.uid()::text);create policy "owner media update" on storage.objects for update to authenticated using(owner_id=auth.uid()::text);create policy "owner private media read" on storage.objects for select to authenticated using(owner_id=auth.uid()::text or bucket_id in('banners','avatars'));

do $$begin alter publication supabase_realtime add table public.announcements,public.questions,public.answers,public.leaderboards,public.leaderboard_entries,public.notifications;exception when duplicate_object then null;end$$;

-- Minimum PostgREST privileges approved for Vertex web clients. RLS remains authoritative.
alter table public.tags enable row level security;
create policy "tags public read" on public.tags for select using(true);
grant usage on schema public to anon, authenticated;
grant select on public.competitions,public.organisations,public.competition_tags,public.tags,public.rounds,public.categories,public.competition_organisers,public.profiles to anon;
grant select on public.competitions,public.organisations,public.competition_tags,public.tags,public.rounds,public.categories,public.competition_organisers,public.profiles,public.registrations,public.bookmarks,public.notifications,public.announcements,public.questions,public.answers to authenticated;
grant update on public.profiles,public.competitions,public.notifications to authenticated;
grant insert on public.competitions,public.registrations,public.bookmarks,public.announcements,public.questions,public.answers to authenticated;
grant delete on public.bookmarks to authenticated;
