import {test,expect} from './helpers/test.js';
import {createAccount,login,sessionCredentials} from './helpers/accounts.js';

test('organisation association, custom rounds, direct top X, recovery and role checks',async({page,request},info)=>{
  test.setTimeout(300000);
  page.on('dialog',dialog=>dialog.accept());
  const organiser=await createAccount(page,'organiser','m4extra');
  const owner=await sessionCredentials(page);
  const headers={apikey:owner.SUPABASE_ANON_KEY,Authorization:`Bearer ${owner.token}`};
  const api=owner.SUPABASE_PROJECT_URL;
  await page.getByRole('button',{name:'Log out',exact:true}).click();
  const manager=await createAccount(page,'organisation','m4org');
  const orgAuth=await sessionCredentials(page);
  const orgSlug=`m4-org-${organiser.username.replace('_','-')}`;
  await page.getByLabel('Organisation name',{exact:true}).fill('Vertex E2E Competition School');
  await page.getByRole('textbox',{name:/^Organisation slug/}).fill(orgSlug);
  await page.getByRole('button',{name:'Create organisation',exact:true}).click();
  await expect(page.locator('[data-org-status]')).toContainText('Organisation saved');
  await page.getByLabel('Organiser username').fill(organiser.username);
  await page.getByRole('button',{name:'Send invitation'}).click();
  await expect(page.locator('[data-invite-status]')).toContainText('Invitation sent');
  await page.getByRole('button',{name:'Log out',exact:true}).click();
  await login(page,organiser,'/organisations');
  await page.getByRole('button',{name:'Accept invitation'}).click();
  await expect(page.locator('[data-org-status]')).toContainText('Invitation accepted');
  await page.goto('/organiser/competition/new');
  await page.getByLabel('Competition name',{exact:true}).fill('Vertex E2E Custom Challenge');
  const slug=`m4-custom-${organiser.username.replace('_','-')}`;
  await page.getByLabel('Competition address',{exact:true}).fill(slug);
  await page.getByLabel('Description',{exact:true}).fill('Custom rounds from a school with an associated organiser.');
  await page.getByLabel('Prize details',{exact:true}).fill('Books and recognition.');
  await page.getByRole('checkbox',{name:'research',exact:true}).check();
  await page.getByLabel('Associated organisation').selectOption({label:'Vertex E2E Competition School'});
  const step=name=>page.getByRole('button',{name:new RegExp(`^\\d ${name}$`)}).click();
  await step('Participation');
  await page.getByLabel('Participation mode').selectOption('both');
  await page.getByLabel('Minimum team size',{exact:true}).fill('2');
  await page.getByLabel('Maximum team size',{exact:true}).fill('4');
  await step('Timeline');
  await page.getByLabel('Competition structure').selectOption('directx');
  await page.getByLabel('Top X winners',{exact:true}).fill('7');
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await expect(page.locator('[data-competition-status]')).toContainText('Draft saved');
  await page.getByLabel('Competition structure').selectOption('custom');
  await page.getByRole('button',{name:'Add round',exact:true}).click();
  await page.locator('[data-round]').nth(0).getByLabel('Round name',{exact:true}).fill('Qualifiers');
  await page.locator('[data-round]').nth(0).getByLabel('Round address',{exact:true}).fill('qualifiers');
  await page.locator('[data-round]').nth(0).getByLabel('Top X advancing',{exact:true}).fill('20');
  await page.locator('[data-round]').nth(1).getByLabel('Top X winners',{exact:true}).fill('7');
  await page.getByRole('button',{name:'Move round 2 up'}).click();
  await expect(page.locator('[data-round]').nth(1).getByLabel('Round name',{exact:true})).toHaveValue('Qualifiers');
  await page.getByRole('button',{name:'Move round 1 down'}).click();
  await page.getByRole('button',{name:'Add round',exact:true}).click();
  await page.getByRole('button',{name:'Remove round 3',exact:true}).click();
  await page.getByLabel('Registration opens',{exact:true}).fill('2027-03-01T09:00');
  await page.getByLabel('Registration deadline',{exact:true}).fill('2027-03-02T09:00');
  await page.getByLabel('Competition starts',{exact:true}).fill('2027-03-03T09:00');
  for(let i=0;i<2;i++){
    const r=page.locator('[data-round]').nth(i),day=`0${4+i}`;
    await r.getByLabel('Round opens',{exact:true}).fill(`2027-03-${day}T09:00`);
    await r.getByLabel('Submission deadline',{exact:true}).fill(`2027-03-${day}T12:00`);
    await r.getByLabel('Results release',{exact:true}).fill(`2027-03-${day}T15:00`);
  }
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:`test-results/m4-timeline-${info.project.name}.png`,fullPage:true});
  await page.route('**/rest/v1/rpc/save_competition',r=>r.abort('failed'));
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await expect(page.locator('[data-competition-status]')).toContainText('Could not reach Vertex');
  await page.unroute('**/rest/v1/rpc/save_competition');
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await expect(page.locator('[data-competition-status]')).toContainText('Draft saved');
  const c=(await(await request.get(`${api}/rest/v1/competitions?slug=eq.${slug}`,{headers})).json())[0];
  const raw=await(await request.get(`${api}/rest/v1/competition_rounds?competition_id=eq.${c.id}&order=sequence`,{headers})).json();
  const rounds=raw.map(({competition_id,status,judging_state,leaderboard_state,...r})=>r);
  for(const details of [{...c,minimum_age:30,maximum_age:10},{...c,registration_opens_at:'2028-01-01T00:00:00Z'},{...c,starts_at:'infinity'}]){
    const r=await request.post(`${api}/rest/v1/rpc/save_competition`,{headers,data:{details,rounds,expected_version:c.version}});expect(r.ok()).toBe(false);
  }
  const orgDenied=await request.post(`${api}/rest/v1/rpc/save_competition`,{headers:{...headers,Authorization:`Bearer ${orgAuth.token}`},data:{details:c,rounds,expected_version:c.version}});
  expect(orgDenied.status()).toBe(403);
  await step('Appearance');
  await page.getByLabel('Banner style').selectOption('gradient');
  await step('Review');
  await page.getByRole('button',{name:'Publish competition',exact:true}).click();
  await expect(page.locator('[data-competition-status]')).toContainText('Competition published');
  await page.goto(`/organisation/${orgSlug}`);
  await expect(page.getByRole('link',{name:/Vertex E2E Custom Challenge/})).toBeVisible();
  await page.getByRole('link',{name:/Vertex E2E Custom Challenge/}).click();
  await expect(page.getByRole('heading',{name:'Vertex E2E Custom Challenge',exact:true})).toBeVisible();
  await page.getByRole('switch').click();
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
  await expect(page.getByRole('heading',{name:'Vertex E2E Custom Challenge',exact:true})).toBeVisible();
  await expect(page.locator('#vertex-splash')).toBeHidden();
  await page.screenshot({path:`test-results/m4-dark-${info.project.name}.png`,fullPage:true});
  await page.screenshot({path:`test-results/m4-dark-viewport-${info.project.name}.png`});
  await page.goto('/profile/edit');await page.getByRole('button',{name:'Log out',exact:true}).click();
  await createAccount(page,'organiser','m4outsider');
  const outsider=await sessionCredentials(page);
  await page.goto(`/organiser/competition/${slug}`);
  await expect(page.getByRole('heading',{name:'Competition unavailable.'})).toBeVisible();
  const denied=await request.post(`${api}/rest/v1/rpc/save_competition`,{headers:{...headers,Authorization:`Bearer ${outsider.token}`},data:{details:c,rounds,expected_version:c.version}});expect(denied.status()).toBe(403);
  const crossUpload=await request.post(`${api}/storage/v1/object/competition-banners/${owner.userId}/${c.id}/${crypto.randomUUID()}.png`,{headers:{...headers,Authorization:`Bearer ${outsider.token}`,'Content-Type':'image/png'},data:Buffer.from('not-an-image')});expect(crossUpload.ok()).toBe(false);
});
