import { test, expect } from './helpers/test.js';
import { createAccount, sessionCredentials } from './helpers/accounts.js';

const step = (page,name) => page.getByRole('button',{name:new RegExp(`^\\d ${name}$`)}).click();
const status = page => page.locator('[data-competition-status]');
async function basics(page,name,slug) {
  await page.goto('/organiser/competition/new');
  await page.getByLabel('Competition name',{exact:true}).fill(name);
  await page.getByLabel('Competition address',{exact:true}).fill(slug);
  await page.getByLabel('Description',{exact:true}).fill('A real student design challenge. Build, explain, and present a thoughtful response.');
  await page.getByLabel('Prize details',{exact:true}).fill('Recognition for the top entries and a design book for each winner.');
  await page.getByRole('checkbox',{name:'design',exact:true}).check();
}
async function timeline(page,multi=false) {
  await step(page,'Timeline');
  await page.getByLabel('Registration opens',{exact:true}).fill('2027-01-01T09:00');
  await page.getByLabel('Registration deadline',{exact:true}).fill('2027-02-01T09:00');
  await page.getByLabel('Competition starts',{exact:true}).fill('2027-02-02T09:00');
  if(multi) await page.getByLabel('Competition structure').selectOption('100-30-3');
  const rounds=page.locator('[data-round]');
  for(let i=0;i<(multi?3:1);i++) {
    const round=rounds.nth(i), day=String(3+i*3).padStart(2,'0');
    await round.getByLabel('Round opens',{exact:true}).fill(`2027-02-${day}T09:00`);
    await round.getByLabel('Submission deadline',{exact:true}).fill(`2027-02-${day}T12:00`);
    await round.getByLabel('Judging starts (optional)',{exact:true}).fill(`2027-02-${day}T13:00`);
    await round.getByLabel('Judging ends (optional)',{exact:true}).fill(`2027-02-${day}T14:00`);
    await round.getByLabel('Results release',{exact:true}).fill(`2027-02-${day}T15:00`);
  }
}
async function publish(page) {
  await step(page,'Review');
  await page.getByRole('button',{name:'Publish competition',exact:true}).click();
  await expect(status(page)).toContainText('Competition published');
}
test('complete competition authoring, publication, validation and access boundaries',async({page,browser,request},info)=>{
  test.setTimeout(300000);
  page.on('dialog',dialog=>dialog.accept());
  const account=await createAccount(page,'organiser','m4');
  const credentials=await sessionCredentials(page);
  const headers={apikey:credentials.SUPABASE_ANON_KEY,Authorization:`Bearer ${credentials.token}`};
  const endpoint=credentials.SUPABASE_PROJECT_URL;
  const publicHeaders={apikey:credentials.SUPABASE_ANON_KEY,Authorization:`Bearer ${credentials.SUPABASE_ANON_KEY}`};
  const slug=`m4-${account.username.replace('_','-')}`;
  await page.getByRole('link',{name:'Manage competitions'}).click();
  await expect(page.getByRole('heading',{name:'Your competitions.'})).toBeVisible();
  await basics(page,'Individual Design Challenge',slug);
  await step(page,'Participation');
  await page.getByLabel('Minimum age',{exact:true}).fill('20');
  await page.getByLabel('Maximum age',{exact:true}).fill('12');
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await expect(status(page)).toContainText('Age range');
  await page.getByLabel('Minimum age',{exact:true}).fill('12');
  await page.getByLabel('Maximum age',{exact:true}).fill('20');
  await page.getByLabel('Categories (one per line)').fill('Junior\nSenior');
  await timeline(page);
  await page.getByLabel('Registration deadline',{exact:true}).fill('2026-12-01T09:00');
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await expect(status(page)).toContainText('Registration must open before');
  await page.getByLabel('Registration deadline',{exact:true}).fill('2027-02-01T09:00');
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await expect(status(page)).toContainText('Draft saved');
  const draftRows=await (await request.get(`${endpoint}/rest/v1/competitions?slug=eq.${slug}`,{headers})).json();
  expect(draftRows).toHaveLength(1);
  const draft=draftRows[0];
  expect(await(await request.get(`${endpoint}/rest/v1/competitions?id=eq.${draft.id}`,{headers:publicHeaders})).json()).toEqual([]);
  await page.goto('/organiser');
  await page.getByRole('link',{name:/Individual Design Challenge/}).click();
  await expect(page.getByLabel('Competition name',{exact:true})).toHaveValue('Individual Design Challenge');
  await page.reload();
  await expect(page.getByLabel('Competition address',{exact:true})).toHaveValue(slug);
  await publish(page);
  await step(page,'Essentials');
  await expect(page.getByRole('checkbox',{name:'design',exact:true})).toBeDisabled();
  await page.getByLabel('Competition name',{exact:true}).fill('Individual Design Challenge Updated');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await expect(status(page)).toContainText('Competition published');
  await basics(page,'Duplicate address',slug);
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await expect(status(page)).toContainText('already in use');
  await page.getByLabel('Competition address',{exact:true}).fill(`${slug}-team`);
  await page.getByLabel('Competition name',{exact:true}).fill('Team Design Challenge');
  await step(page,'Participation');
  await page.getByLabel('Participation mode').selectOption('team');
  await page.getByLabel('Minimum team size',{exact:true}).fill('2');
  await page.getByLabel('Maximum team size',{exact:true}).fill('5');
  await page.getByLabel('Categories (one per line)').fill('Product design\nDigital design');
  await timeline(page,true);
  await step(page,'Appearance');
  await page.getByLabel('Banner style').selectOption('image');
  await page.getByLabel('Banner image',{exact:false}).setInputFiles('assets/logo.png');
  await expect(status(page)).toContainText('Banner ready');
  await page.getByLabel('Certificate template status').selectOption('planned');
  await page.getByLabel('Certificate availability',{exact:true}).fill('2027-02-12T09:00');
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await expect(status(page)).toContainText('Draft saved');
  const team=(await(await request.get(`${endpoint}/rest/v1/competitions?slug=eq.${slug}-team`,{headers})).json())[0];
  expect(team.banner_path).toBeTruthy();
  const signUrl=`${endpoint}/storage/v1/object/sign/competition-banners/${team.banner_path}`;
  expect((await request.post(signUrl,{headers:publicHeaders,data:{expiresIn:60}})).ok()).toBe(false);
  await publish(page);
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:`test-results/m4-review-${info.project.name}.png`,fullPage:true});
  const published=(await(await request.get(`${endpoint}/rest/v1/competitions?id=eq.${team.id}`,{headers})).json())[0];
  const rounds=await(await request.get(`${endpoint}/rest/v1/competition_rounds?competition_id=eq.${team.id}&order=sequence`,{headers})).json();
  expect(rounds.map(r=>r.advancement_count)).toEqual([100,30,3]);
  const roundPayload=rounds.map(({competition_id,status,judging_state,leaderboard_state,...r})=>r);
  const changed=await request.post(`${endpoint}/rest/v1/rpc/save_competition`,{headers,data:{details:{...published,minimum_team_size:3},rounds:roundPayload,expected_version:published.version}});
  expect(changed.ok()).toBe(false);expect(await changed.text()).toContain('locked');
  const stale=await request.post(`${endpoint}/rest/v1/rpc/save_competition`,{headers,data:{details:published,rounds:roundPayload,expected_version:1}});
  expect(stale.ok()).toBe(false);expect(await stale.text()).toContain('another tab');
  expect((await request.patch(`${endpoint}/rest/v1/competitions?id=eq.${team.id}`,{headers,data:{owner_id:crypto.randomUUID()}})).ok()).toBe(false);
  const publicContext=await browser.newContext({baseURL:'http://127.0.0.1:4173',viewport:info.project.use.viewport});
  const guest=await publicContext.newPage();
  await guest.goto(`/competition/${slug}-team`);
  await expect(guest.getByRole('heading',{name:'Team Design Challenge',exact:true})).toBeVisible();
  await expect(guest.getByText('Coming Soon',{exact:true})).toBeVisible();
  await expect(guest.getByText('Top 100 advance',{exact:true})).toBeVisible();
  await expect(guest.locator('.competition-banner img')).toBeVisible();
  await guest.reload();await expect(guest.getByRole('heading',{name:'Team Design Challenge',exact:true})).toBeVisible();
  await guest.screenshot({path:`test-results/m4-public-${info.project.name}.png`,fullPage:true});
  await guest.screenshot({path:`test-results/m4-public-viewport-${info.project.name}.png`});
  expect(await guest.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await guest.goto('/discover');await expect(guest.locator(`a[href="/competition/${slug}-team"]`)).toBeVisible();
  await guest.goto(`/organiser/competition/${slug}-team`);await expect(guest).toHaveURL(/\/login\?returnTo=/);
  await publicContext.close();
  // Replace the test upload through the actual editor; application removes the old object.
  await step(page,'Appearance');
  await page.getByLabel('Banner style').selectOption('gradient');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await expect(status(page)).toContainText('Competition published');
  const files=await request.post(`${endpoint}/storage/v1/object/list/competition-banners`,{headers,data:{prefix:`${credentials.userId}/${team.id}`,limit:100}});
  expect(await files.json()).toEqual([]);
  await page.goto('/profile/edit');await page.getByRole('button',{name:'Log out',exact:true}).click();
  await createAccount(page,'participant','m4participant');
  await page.goto(`/organiser/competition/${slug}-team`);
  await expect(page.getByRole('heading',{name:'Organiser account required.'})).toBeVisible();
  const participant=await sessionCredentials(page);
  const denied=await request.post(`${endpoint}/rest/v1/rpc/save_competition`,{headers:{...headers,Authorization:`Bearer ${participant.token}`},data:{details:published,rounds:roundPayload,expected_version:published.version}});
  expect(denied.status()).toBe(403);
});
