import { test,expect,anotherPage } from './helpers/test.js';
import { createAccount,sessionCredentials } from './helpers/accounts.js';
import { nativeApp,displayedPushes } from './helpers/installed-app.js';
import { randomUUID } from 'node:crypto';
import { workerUpdateServer } from './helpers/worker-update-server.js';

test('real installation, browser subscription and announcement/result/deadline delivery',async({page,request},info)=>{
  test.setTimeout(600000);
  const native=await nativeApp();
  const person=native.page;
  try {
    await person.goto('/app');
    await expect(person.locator('[data-device-banner] [data-install-app]')).toBeVisible({timeout:30000});
    await person.getByRole('button',{name:'Dismiss install banner'}).click();
    await person.reload();
    await expect(person.locator('[data-device-banner]')).toBeEmpty();
    await person.goto('/discover');
    await expect(person.locator('[data-device-banner]')).toBeEmpty();
    const participant=await createAccount(person,'participant','m20');
    const access=await sessionCredentials(person);
    await person.goto('/app');
    expect(await person.evaluate(()=>Notification.permission)).toBe('default');
    expect(await person.evaluate(async()=>Boolean(await(await navigator.serviceWorker.ready).pushManager.getSubscription()))).toBe(false);
    const app=await native.install();
    console.log('Native installation and standalone launch complete.');
    await expect(app.getByRole('heading',{name:'Vertex is open as an app.'})).toBeVisible();
    expect(await app.evaluate(()=>matchMedia('(display-mode: standalone)').matches)).toBe(true);
    await native.context.grantPermissions(['notifications'],{origin:'http://127.0.0.1:4173'});
    await app.getByRole('button',{name:'Enable notifications',exact:true}).click();
    console.log('Browser subscription requested.');
    try {await expect(app.locator('.device-state')).toHaveText('On',{timeout:60000});}
    catch(error){console.log('Subscription status:',await app.locator('[data-push-status]').textContent());throw error;}
    await expect(app.locator('[data-push-status]')).toContainText('Device notifications enabled.');
    console.log('Real browser subscription saved.');
    await expect(app.locator('#vertex-splash')).toHaveCount(0);
    await app.evaluate(()=>{document.activeElement?.blur();scrollTo({top:0,behavior:'instant'});});
    await app.screenshot({path:info.outputPath('installed-desktop.png'),fullPage:true});
    await app.reload();
    await expect(app.locator('.device-state')).toHaveText('On');
    const sub=await app.evaluate(async()=> (await(await navigator.serviceWorker.ready).pushManager.getSubscription()).toJSON());
    expect(sub.endpoint).toMatch(/^https:\/\/fcm.googleapis.com\//);
    expect(sub.keys.p256dh).toHaveLength(87);
    const root=`${access.SUPABASE_PROJECT_URL}/rest/v1`;
    const headers=token=>({apikey:access.SUPABASE_ANON_KEY,Authorization:`Bearer ${token}`,'content-type':'application/json'});
    const rpc=async(token,name,data={})=>{const r=await request.post(`${root}/rpc/${name}`,{headers:headers(token),data});expect(r.ok(),await r.text()).toBe(true);return r.json();};
    const ownerAccount=await createAccount(page,'organiser','m20');
    const owner=await sessionCredentials(page);
    const own=await request.get(`${root}/push_subscriptions`,{headers:headers(access.token)});
    expect((await own.json()).map(row=>row.user_id)).toEqual([access.userId]);
    const foreign=await request.get(`${root}/push_subscriptions`,{headers:headers(owner.token)});
    expect(await foreign.json()).toEqual([]);
    for(const name of ['push_worker_keys','push_claim_batch','push_worker_authorized']){
      const denied=await request.post(`${root}/rpc/${name}`,{headers:headers(access.token),data:{}});expect(denied.ok()).toBe(false);
    }
    const direct=await request.post(`${root}/push_subscriptions`,{headers:headers(access.token),data:{user_id:access.userId,...sub}});expect(direct.ok()).toBe(false);
    const invalid=await request.post(`${root}/rpc/save_push_subscription`,{headers:headers(access.token),data:{subscription:{...sub,endpoint:'https://example.org/private'},app_origin:'http://127.0.0.1:4173'}});expect(invalid.ok()).toBe(false);
    const id=randomUUID(),round=randomUUID(),slug=`m20-${ownerAccount.username.replaceAll('_','-')}`;
    const now=Date.now(),at=seconds=>new Date(now+seconds*1000).toISOString();
    const details={id,slug,name:`Vertex M20 ${ownerAccount.username}`,status:'published',field_tags:['design'],prize_details:'Recognition for thoughtful work.',description:'PWA delivery acceptance fixture.',minimum_age:12,maximum_age:25,team_mode:'individual',categories:[],structure:'direct3',banner_kind:'colour',banner_colour:'#2563eb',banner_colour_end:'#0b1120',banner_path:null,certificate_status:'not_planned',registration_opens_at:at(-600),registration_closes_at:at(40),starts_at:at(41)};
    await rpc(owner.token,'save_competition',{details,rounds:[{id:round,name:'Final',slug:'final',sequence:1,advancement_count:3,opens_at:at(42),submission_deadline:at(60),leaderboard_releases_at:at(61)}]});
    await app.goto(`/competition/${slug}/register`);
    await app.getByRole('button',{name:'Confirm registration'}).click();
    await expect(app.getByRole('heading',{name:"You're registered."})).toBeVisible();
    const reminder=randomUUID(),reminderSlug=slug+'-saved';
    await rpc(owner.token,'save_competition',{details:{...details,id:reminder,slug:reminderSlug,name:'M20 saved deadline '+ownerAccount.username,registration_closes_at:at(7200),starts_at:at(7201)},rounds:[{id:randomUUID(),name:'Final',slug:'final',sequence:1,advancement_count:3,opens_at:at(7202),submission_deadline:at(7300),leaderboard_releases_at:at(7301)}]});
    await app.goto(`/competition/${reminderSlug}`);
    await app.locator(`[data-bookmark="${reminder}"]`).click();
    await expect(app.locator(`[data-bookmark="${reminder}"]`)).toHaveAttribute('aria-pressed','true');
    // Keep announcements unread while the real cron and FCM transport deliver.
    await app.goto('/app');
    await page.goto(`/competition/${slug}/announcements`);
    await page.getByLabel('Heading').fill('M20 real push briefing');
    await page.getByLabel('Message').fill('Your installed Vertex app received this organiser update.');
    await page.getByRole('button',{name:'Publish announcement'}).click();
    await expect(page.locator('[data-announcement-status]')).toContainText('Announcement published.');
    await expect.poll(async()=>JSON.stringify(await displayedPushes(app)),{timeout:180000,intervals:[2000]}).toContain('M20 real push briefing');
    await expect.poll(async()=>JSON.stringify(await displayedPushes(app)),{timeout:90000,intervals:[2000]}).toContain('Registration closes soon');
    await page.goto(`/organiser/competition/${slug}/scoring?round=final`);
    await page.locator('[data-criterion-form] [name="name"]').fill('Total');
    await page.getByLabel('Maximum marks').fill('100');
    await page.getByRole('button',{name:'Save criterion'}).click();
    await expect(page.locator('.scoring-criteria-list')).toContainText('Total');
    const row=page.locator('.scoring-entry').filter({hasText:participant.name});
    await row.getByRole('button',{name:'Enter marks'}).click();
    await row.locator('[data-criterion-id]').fill('99');
    await row.getByRole('button',{name:'Save marks'}).click();
    await expect(row).toHaveClass(/\bcomplete\b/);
    await page.goto(`/organiser/competition/${slug}/advancement?round=final`);
    page.once('dialog',dialog=>dialog.accept());
    await page.getByRole('button',{name:'Finalise round'}).click();
    await expect(page.getByRole('heading',{name:'Round locked.'})).toBeVisible();
    await expect.poll(()=>Date.now(),{timeout:90000}).toBeGreaterThan(now+61000);
    await page.goto(`/organiser/competition/${slug}/leaderboards?round=final`);
    page.once('dialog',dialog=>dialog.accept());
    await page.getByRole('button',{name:'Publish now'}).click();
    await expect(page.locator('.leaderboard-state')).toHaveText('Published');
    await expect.poll(async()=>JSON.stringify(await displayedPushes(app)),{timeout:180000,intervals:[2000]}).toContain('leaderboard');
    const pushes=await displayedPushes(app);
    expect(pushes.some(item=>item.path===`/competition/${slug}/leaderboard/final`)).toBe(true);
    const reminders=await request.get(`${root}/notifications?kind=eq.deadline_reminder&competition_id=eq.${reminder}`,{headers:headers(access.token)});
    expect(await reminders.json()).toHaveLength(1);
    await app.goto('/notifications');
    await expect(app.locator('.device-state')).toHaveText('On');
    await app.getByRole('checkbox',{name:/Announcements/}).uncheck();
    await app.getByRole('button',{name:'Save notification choices'}).click();
    await expect(app.locator('[data-push-status]')).toContainText('Notification choices saved');
    await app.reload();
    await expect(app.getByRole('checkbox',{name:/Announcements/})).not.toBeChecked();
    await app.getByRole('button',{name:'Turn off on this device'}).click();
    await expect(app.locator('.device-state')).toHaveText('Off');
    expect(await app.evaluate(async()=>await(await navigator.serviceWorker.ready).pushManager.getSubscription())).toBe(null);
    const removed=await request.get(`${root}/push_subscriptions`,{headers:headers(access.token)});expect(await removed.json()).toEqual([]);
    await app.getByRole('button',{name:'Enable notifications',exact:true}).click();
    await expect(app.locator('.device-state')).toHaveText('On',{timeout:60000});
    await app.goto('/profile/edit');
    await app.getByRole('button',{name:'Log out',exact:true}).last().click();
    await expect(app).toHaveURL(/\/login$/);
    const signedOut=await request.get(`${root}/push_subscriptions`,{headers:headers(access.token)});expect(await signedOut.json()).toEqual([]);
    expect(await displayedPushes(app)).toEqual([]);
  } finally {await native.close();}
});

test('public mobile controls, new session eligibility, unsupported environment and useful offline recovery',async({page,browser},info)=>{
  const native=await nativeApp();
  try{
    await native.page.goto('/app');
    await expect(native.page.locator('[data-device-banner] [data-install-app]')).toBeVisible({timeout:30000});
    await native.page.getByRole('button',{name:'Dismiss install banner'}).click();
    await native.page.reload();
    await expect(native.page.locator('[data-device-banner]')).toBeEmpty();
  }finally{await native.close();}
  const next=await nativeApp();
  try{
    await next.page.goto('/app');
    await expect(next.page.locator('[data-device-banner] [data-install-app]')).toBeVisible({timeout:30000});
    await next.page.evaluate(()=>navigator.serviceWorker.ready);
    await next.page.reload();
    await next.context.setOffline(true);
    await next.page.goto('/competition/offline-route/leaderboard/final');
    await expect(next.page.getByRole('heading',{name:/Your connection/})).toBeVisible();
    await next.page.screenshot({path:info.outputPath('offline-desktop.png'),fullPage:true});
    expect(await next.page.evaluate(async()=>{const keys=await caches.keys();const urls=[];for(const key of keys)for(const item of await(await caches.open(key)).keys())urls.push(item.url);return urls.every(url=>url.startsWith(location.origin)&&!url.includes('/rest/')&&!url.includes('/auth/'));})).toBe(true);
    await next.context.setOffline(false);
    await next.page.getByRole('link',{name:/discovery/i}).click();
    await expect(next.page.getByRole('heading',{name:'Find your next challenge.'})).toBeVisible();
    await createAccount(next.page,'participant','m20');
    await next.page.goto('/app');
    await next.page.evaluate(()=>{window.subscribeCalls=0;const original=PushManager.prototype.subscribe;PushManager.prototype.subscribe=function(...args){window.subscribeCalls++;return original.apply(this,args);};});
    await next.page.getByRole('button',{name:'Enable notifications',exact:true}).click();
    await expect(next.page.locator('[data-push-status]')).toContainText('Install Vertex first.');
    expect(await next.page.evaluate(()=>Notification.permission)).toBe('default');
    expect(await next.page.evaluate(()=>window.subscribeCalls)).toBe(0);
  }finally{await next.close();}
  const mobile=await anotherPage(browser,320);
  await mobile.addInitScript(()=>{delete window.PushManager;});
  await createAccount(mobile,'participant','m20');
  await mobile.goto('/app');
  await expect(mobile.locator('[data-device-controls]')).toContainText('does not support device notifications');
  await expect(mobile.locator('#vertex-splash')).toHaveCount(0);
  expect(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await mobile.screenshot({path:info.outputPath('unsupported-mobile.png'),fullPage:true});
  await mobile.getByRole('switch',{name:/Switch to dark mode/}).click();
  await mobile.emulateMedia({reducedMotion:'reduce'});
  await mobile.reload();
  await expect(mobile.locator('[data-device-controls]')).toContainText('does not support device notifications');
  await mobile.screenshot({path:info.outputPath('unsupported-mobile-dark.png'),fullPage:true});
  await mobile.context().close();
  await page.goto('/app');
  await expect(page.locator('[data-device-controls]')).toContainText('Log in');
  await page.reload();
  await expect(page.getByRole('heading',{name:'On this device.'})).toBeVisible();
  const update=await workerUpdateServer();
  try{
    await page.goto(update.origin+'/app');
    await page.evaluate(()=>navigator.serviceWorker.ready);
    await page.reload();
    await expect(page.getByRole('heading',{name:'On this device.'})).toBeVisible();
    await expect(page.locator('[data-device-controls]')).toContainText('Log in');
    update.deploy();
    await page.evaluate(async()=>{const reg=await navigator.serviceWorker.getRegistration();await reg.update();});
    await expect(page.getByRole('button',{name:'Reload to update'})).toBeVisible({timeout:30000});
    await expect(page.locator('[data-device-banner]')).toContainText('Save any edits');
    expect(await page.evaluate(async()=>{const reg=await navigator.serviceWorker.getRegistration();return Boolean(reg.waiting);})).toBe(true);
    await page.getByRole('button',{name:'Reload to update'}).click();
    await expect(page.getByRole('heading',{name:'On this device.'})).toBeVisible();
    await expect.poll(()=>page.evaluate(async()=>{const reg=await navigator.serviceWorker.getRegistration();return Boolean(reg.waiting);})).toBe(false);
    await expect(page.locator('[data-device-banner]')).toBeEmpty();
  }finally{await page.goto('about:blank');await update.close();}
});
